version: '3.9'

services:
  server:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
    restart: always
    ports:
      - "8080:80"

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    user: ${UID}:${GID}
    volumes:
      - ./:/var/www
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
